name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  basic-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.0.8
    with:
      working_directory: './_example/default_subnet/'

  complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.0.8
    with:
      working_directory: './_example/name-specific_subnet/'

  vnet_with_existing_ddos_id-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.0.8
    with:
      working_directory: './_example/nat-gateway_subnet/'
