name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  basic-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.3.6
    with:
      working_directory: './examples/basic/'

  complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.3.6
    with:
      working_directory: './examples/complete/'

  name-specific_subnet:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.3.6
    with:
      working_directory: './examples/name-specific_subnet/'

  nat-gateway_subnet:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.3.6
    with:
      working_directory: './examples/nat-gateway_subnet/'
